# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pace < Formula
  desc "Visual timer for the command line"
  homepage "https://github.com/swartzrock/pace"
  url "https://github.com/swartzrock/pace/archive/0.3.0.tar.gz"
  sha256 "183ce1aa8e7673509c220029a88cddc45d88ccc39eb65b1b1decfaad9a371ee2"
  license "ISC"

  on_macos do
    on_intel do
      url "https://github.com/swartzrock/pace/releases/download/0.3.0/pace-0.3.0-darwin-amd64.tar.gz"
      sha256 "4e8e47a7c681b92181c68a19736d50187a3da0464f0d38e9438412d839a99d57"
    end

    on_arm do
      url "https://github.com/swartzrock/pace/releases/download/0.3.0/pace-0.3.0-darwin-arm64.tar.gz"
      sha256 "4e8e47a7c681b92181c68a19736d50187a3da0464f0d38e9438412d839a99d57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swartzrock/pace/releases/download/0.3.0/pace-0.3.0-linux-amd64.tar.gz"
      sha256 "875917d012050300e8686acf997dce1a1374737ef1b81981ed02c28b524d186c"
    end

    on_arm do
      url "https://github.com/swartzrock/pace/releases/download/0.3.0/pace-0.3.0-linux-arm64.tar.gz"
      sha256 "c912daa37e54cc04e88990360b24a1c46c187455adb3f0223395fc330e1390c5"
    end
  end

  def install
    bin.install "pace"
  end
end
